# Let's prep our data

### Get the data

- Download to your computer <a href="https://drive.google.com/file/d/1-798fq909hN3x3UxBYUDZrkEaPTliyvJ/view?usp=sharing"> this 256MB file</a> that contains NYPD summons data from 2015-2025s.

In [4]:
## import libraries
import pandas as pd

In [5]:
# import data
nypd_summons = pd.read_csv("summons-15-25.csv")
nypd_summons.info()

<class 'pandas.DataFrame'>
RangeIndex: 1384334 entries, 0 to 1384333
Data columns (total 18 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   SUMMONS_KEY            1384334 non-null  int64
 1   SUMMONS_DATE           1384334 non-null  str
 2   OFFENSE_DESCRIPTION    1384316 non-null  str
 3   LAW_SECTION_NUMBER     1348831 non-null  str
 4   LAW_DESCRIPTION        1309406 non-null  str
 5   SUMMONS_CATEGORY_TYPE  1309321 non-null  str
 6   AGE_GROUP              1354372 non-null  str
 7   SEX                    1284382 non-null  str
 8   RACE                   964769 non-null   str
 9   JURISDICTION_CODE      1384334 non-null  int64
 10  BORO                   1372084 non-null  str
 11  PRECINCT_OF_OCCUR      1384334 non-null  int64
 12  X_COORDINATE_CD        1383871 non-null  float64
 13  Y_COORDINATE_CD        1383871 non-null  float64
 14  Latitude               1383870 non-null  float64
 15  Longitude              1383870 non-null  float64
 16  Lon_Lat                1383870 non-null  str
 17  YEAR                   1384334 non-null  int64
dtypes: float64(4), int64(4), str(10)
memory usage: 190.1 MB

## Doesn't AI make learning coding obsolete?

Yes, it's excellent at data analysis and coding. 

But here are a few problems you might run into:

- How will you investigate AI-related topics?
- Hitting Limits – even with paid accounts.
- Protecting sources.
- Not infallibable.

At Bloomberg, the rule is **you are responsible** for every number, analysis and finding you put into your pieces.

So be prepared to understand and explain each of your decisions, including AI's guidance.

## Traditonal coding v. Vibe Coding

**Traditional coding**
- structured approach to learning syntax and rules first.

**Vibe coding**
- learning by experimenting, observing results, analyzing and iterating – with AI's assistance – rather than memorizing syntax.

- still need to learn coding because you must understand what the code is doing, recognizing mistakes and incorrect interpretations of your prompts.

So you need to retain control of your editorial decisions and process. AI can help write code, but understanding coding helps you trust — or question — the answers.

What are some things - terms, processes etc – that we learned so far?
- Python is good at math
- variables are characters in your data.
- PEMDAS
- f-strings
- built in functions
    - like what? len, type, print, abs, round
- importing and reading data
- understanding dataframes v. series
- getting an overview of your data

# Interviewing Data

If AI can write the code, what questions might you ask based on your domain/beat knowledge?

Let's step back to see how we <a href="https://docs.google.com/presentation/d/1oA50DVvcPT2IWDAHTXogD5lWsWk1TVq_sp5iIS1qQv8/edit?usp=sharing">"interview"</a> data.

## Interviewing Data with AI

In [6]:
## Get a sample. 
nypd_summons.sample(10)

,SUMMONS_KEY,SUMMONS_DATE,OFFENSE_DESCRIPTION,LAW_SECTION_NUMBER,LAW_DESCRIPTION,SUMMONS_CATEGORY_TYPE,AGE_GROUP,SEX,RACE,JURISDICTION_CODE,BORO,PRECINCT_OF_OCCUR,X_COORDINATE_CD,Y_COORDINATE_CD,Latitude,Longitude,Lon_Lat,YEAR
538188,299129383,2025-01-09,CONGREGATES WITH OTHER PERSONS IN PUBLIC AND R...,240.20(6),(null),(null),(null),(null),WHITE HISPANIC,0,QUEENS,115,1022286.0,213223.0,40.751851,-73.862718,POINT (-73.862718 40.751851),2025
961861,154075830,2016-06-15,UNLICENSED OPERATOR,509,VTL,VTL,45-64,F,NaN,0,QUEENS,106,1026021.0,185039.0,40.674476,-73.849414,POINT (-73.84941388699998 40.67447573000004),2016
474253,186574712,2018-08-18,HOURS; PERMITTED TO BE IN PARK BETWEEN 6AM-1AM...,1-03(A)(1),NaN,NaN,18-24,M,BLACK,0,QUEENS,105,1058026.0,208590.0,40.738909,-73.733776,POINT (-73.73377601 40.73890851),2018
944780,154560345,2016-07-03,"FIREWORKS, POSSESS/USE",270,Penal Law,FIREWORKS,45-64,M,NaN,0,BRONX,45,1037232.0,235825.0,40.813810,-73.808597,POINT (-73.80859746899995 40.81381026700007),2016
485100,184915774,2018-07-08,CONSUMPTION OF ALCOHOL,10-125,Administrative Code,ALCOHOL,25-44,M,WHITE HISPANIC,0,QUEENS,108,1007144.0,209854.0,40.742656,-73.917382,POINT (-73.91738244 40.74265595),2018
161697,269056077,2023-05-30,ALCOHOLIC BEVERAGE IN PUBLIC,10-125(2B),(null),(null),25-44,M,WHITE HISPANIC,0,QUEENS,115,1023267.0,213110.0,40.751528,-73.859178,POINT (-73.85917815 40.75152814),2023
1292472,142790527,2015-05-09,TRESPASS,140.05,Penal Law,TRESPASS,18-24,M,NaN,0,BROOKLYN,61,990747.0,155849.0,40.594452,-73.976607,POINT (-73.97660735299998 40.59445153400002),2015
418994,196291762,2019-04-22,FEDERAL MOTOR VEH. SAFETY REG,CFR 49,NYS Transportation,NYS TRANS,UNKNOWN,NaN,NaN,0,NEW YORK,7,988082.0,200814.0,40.717872,-73.986178,POINT (-73.98617781499996 40.71787216100006),2019
1093557,148945605,2015-12-15,CONSUMPTION OF ALCOHOL,10-125,Administrative Code,ALCOHOL,25-44,M,NaN,0,BROOKLYN,75,1016768.0,182678.0,40.668034,-73.882783,POINT (-73.88278298299997 40.66803414100008),2015
1167889,146062524,2015-09-08,CONSUMPTION OF ALCOHOL,10-125,Administrative Code,ALCOHOL,25-44,M,NaN,0,QUEENS,109,1038797.0,216816.0,40.761626,-73.803098,POINT (-73.80309809299997 40.76162625200004),2015

1. Which borough had the most summons?
2. How many times did the top 10 most common offenses occur?
3. What are the total number of summons broken down by year?
4. What were some of the most unusual summons? (how do you define most unusual)
5. What is the count of summons by gender?
6. How many summons were issued by race?
7. Which borough had the fewest offenses per 100K people?

### What are some questions you could ask this data?

### Upload data to AI - ask it questions.

#### What happened?

What do we do on deadline when the dataset is too big?

Even if AI ingests a large dataset, it responds by analyzing a fraction of the data.

The importance of <a href="https://docs.google.com/presentation/d/1BKn8iUq9wy3KgrcfbfpJN6i3cnB8dNlnbAQlrbUSGJ0/edit?usp=sharing">Reproducible Data Journalism</a>

## And now let's interview data using Pandas

We are soon going to blend using AI and coding, but first it's important to understand some Pandas fundamentals.

#### Finally **Vibe Coding**!

##### Template for Vibe Coding

1. Give AI a sample of your data (like a 100 rows)
2. Ask it for the Pandas code to answer a question, **but always tell it to comment the code**!
3. Leave a comment in Markdown with your prompt
4. Test it out in a code cell.
5. If the code throws an error, copy the entire code and give it AI.
6. Remember to add this updated prompt to your markdown.
7. Test out the the updated code in same cell.
8. Create a markdown cell in which you use f-strings to leave your finding

#### 1. Give AI a sample of your data (like a 100 rows)

In [7]:
## see sample data
summons_sample = nypd_summons.sample(100)
summons_sample

,SUMMONS_KEY,SUMMONS_DATE,OFFENSE_DESCRIPTION,LAW_SECTION_NUMBER,LAW_DESCRIPTION,SUMMONS_CATEGORY_TYPE,AGE_GROUP,SEX,RACE,JURISDICTION_CODE,BORO,PRECINCT_OF_OCCUR,X_COORDINATE_CD,Y_COORDINATE_CD,Latitude,Longitude,Lon_Lat,YEAR
1062440,150353066,2016-02-09,VENDOR: UNLICENSED,20-453,Administrative Code,VENDING,25-44,M,NaN,1,BROOKLYN,84,990146.0,188389.0,40.683767,-73.978743,POINT (-73.978742975 40.683767303000025),2016
36102,291302216,2024-08-07,FEDERAL MOTOR VEH. SAFETY REG,CFR 49,NYS Transportation,NYS TRANS,UNKNOWN,(null),(null),0,BROOKLYN,94,1001767.0,202300.0,40.721926,-73.936805,POINT (-73.93680499059303 40.72192610196327),2024
1075442,149526583,2016-01-18,URINATING IN PUBLIC,16-1186,Administrative Code,URINATING,25-44,M,NaN,0,MANHATTAN,33,1001528.0,244950.0,40.838998,-73.937559,POINT (-73.93755896999993 40.838997766000034),2016
586832,308529501,2025-06-23,"ENGAGES IN FIGHTING, OR VIOLENT, TUMULTUOUS OR...",240.20(1),(null),(null),<18,M,BLACK,0,QUEENS,101,1044121.0,155673.0,40.593770,-73.784419,POINT (-73.784419 40.59377),2025
986961,153326913,2016-05-21,CONSUMPTION OF ALCOHOL,10-125,Administrative Code,ALCOHOL,45-64,M,UNKNOWN,0,QUEENS,103,1037559.0,194576.0,40.700591,-73.807743,POINT (-73.80774319999993 40.70059059000005),2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201352,261130853,2022-12-30,FEDERAL MOTOR VEH. SAFETY REG,CFR 49,NYS Transportation,NYS TRANS,UNKNOWN,(null),(null),0,BROOKLYN,76,984166.0,188346.0,40.683651,-74.000304,POINT (-74.0003043120176 40.6836512406856),2022
640796,316399569,2025-11-15,LITTER FROM A VEHICLE,16-188(4),(null),(null),25-44,F,BLACK,0,BROOKLYN,75,1014946.0,181023.0,40.663500,-73.889357,POINT (-73.889357 40.6635),2025
619662,313231134,2025-09-16,NO HELMET,1238(5)A,(null),(null),25-44,M,WHITE HISPANIC,0,BRONX,42,1009895.0,240776.0,40.827521,-73.907333,POINT (-73.907333 40.827521),2025
687625,168644605,2017-08-25,DISCON: OBSTRUCT VEHICLE,240.205B,Penal Law,DISORDERLY CONDUCT,18-24,M,WHITE,0,MANHATTAN,18,988626.0,217304.0,40.763133,-73.984205,POINT (-73.98420465299995 40.76313286700002),2017
52221,288351899,2024-06-11,UNREGISTERED VEHICLE,401,VTL,VTL,18-24,M,BLACK HISPANIC,0,BROOKLYN,75,1016803.0,188922.0,40.685166,-73.882622,POINT (-73.882622 40.685166),2024

In [8]:
# Summon the Head 
nypd_summons.head()

,SUMMONS_KEY,SUMMONS_DATE,OFFENSE_DESCRIPTION,LAW_SECTION_NUMBER,LAW_DESCRIPTION,SUMMONS_CATEGORY_TYPE,AGE_GROUP,SEX,RACE,JURISDICTION_CODE,BORO,PRECINCT_OF_OCCUR,X_COORDINATE_CD,Y_COORDINATE_CD,Latitude,Longitude,Lon_Lat,YEAR
0,298767983,2024-12-31,DISORDERLY CONDUCT,240.2,Penal Law,DISORDERLY CONDUCT,45-64,M,WHITE HISPANIC,0,MANHATTAN,14,985927.0,213077.0,40.751523,-73.993947,POINT (-73.99394730218468 40.75152348693427),2024
1,298704187,2024-12-31,IMPROPER PLATES,402,VTL,VTL,18-24,M,ASIAN / PACIFIC ISLANDER,0,BRONX,49,1020823.0,249562.0,40.851589,-73.867801,POINT (-73.86780058180116 40.85158922344624),2024
2,298787872,2024-12-31,TRESPASS,140.05,Penal Law,TRESPASS,25-44,F,BLACK HISPANIC,2,MANHATTAN,32,998922.0,235604.0,40.813352,-73.946996,POINT (-73.946996 40.813352),2024
3,298724988,2024-12-31,FEDERAL MOTOR VEH. SAFETY REG,CFR 49,NYS Transportation,NYS TRANS,UNKNOWN,(null),(null),0,BROOKLYN,94,1001547.0,203048.0,40.723980,-73.937597,POINT (-73.93759674847603 40.72397961334044),2024
4,298704460,2024-12-31,POSSESSION OF ALCOHOL BY A MINOR,65-C,(null),(null),18-24,M,WHITE,0,MANHATTAN,6,984439.0,204595.0,40.728254,-73.999318,POINT (-73.999318 40.728254),2024

In [9]:
## export
summons_sample.to_csv("sample_summons_100.csv", index = False, encoding = "UTF8")

### Explanation of the export code

`summons_sample` is the dataframe we want to export

`.to_csv()` saves our dataframe to a .csv file. You are baseically exporting your python data out into a format that Excel, Google Sheets can read.

`index=False`
By default, on export pandas includes the DataFrame's index – the row numbers (0, 1, 2, 3...). We NEVER
need it 99.99 percent of the time. `index=False` simply tells pandas to leave that column out on export.

`encoding="utf-8"`
Tells Python which character encoding to use when writing the file. `UTF-8` is the most universal standard — it handles English plus accented characters, symbols, non-Latin scripts, etc. without garbling them. If your data has names like "García" or "Müller" and you skip this, you might get weird characters or errors depending on your system.

Recall some questions we want to ask:

1. Which borough had the most summons?
2. How many times did the top 10 most common offenses occur?
3. What are the total number of summons broken down by year?
4. What were some of the most unusual summons? (how do you define most unusual)
5. What is the count of summons by gender?
6. How many summons were issued by race?
7. Which borough had the fewest offenses per 100K people?

## Who wants to share their answers?

# Prompt for all questions #
For all the following questions, use Pandas 2.5 or newer.
Always provide comments for each line of code.

### Prompt: 

Provide the pandas code to calculate which boroughs had the most summons (in descending order).

In [10]:
# 1. Which borough had the most summons? 

# Replace string '(null)' placeholders with real NaN so they're excluded cleanly
nypd_summons['BORO'] = nypd_summons['BORO'].replace('(null)', pd.NA)

# Count summons per borough, sort descending, and drop any missing borough values
borough_counts = (
    nypd_summons['BORO']
    .value_counts()              # Count occurrences of each borough; sorts descending by default
    .reset_index()               # Convert the Series into a two-column DataFrame
    .rename(columns={            # Rename columns from pandas defaults to readable names
        'BORO': 'borough',
        'count': 'summons_count'
    })
)

borough_counts

         borough  summons_count
0       BROOKLYN         427679
1          BRONX         312327
2      MANHATTAN         275884
3         QUEENS         246314
4       NEW YORK          63056
5  STATEN ISLAND          46824

In [11]:
## print the columns
print(nypd_summons.columns.tolist())

['SUMMONS_KEY', 'SUMMONS_DATE', 'OFFENSE_DESCRIPTION', 'LAW_SECTION_NUMBER', 'LAW_DESCRIPTION', 'SUMMONS_CATEGORY_TYPE', 'AGE_GROUP', 'SEX', 'RACE', 'JURISDICTION_CODE', 'BORO', 'PRECINCT_OF_OCCUR', 'X_COORDINATE_CD', 'Y_COORDINATE_CD', 'Latitude', 'Longitude', 'Lon_Lat', 'YEAR']

In [12]:
## define offen

offen = 'OFFENSE_DESCRIPTION'

In [13]:
# 2. What were the top 10 most common offenses?
nypd_summons[offen] = nypd_summons[offen].replace('(null)', pd.NA)

offense_descriptions = (
    nypd_summons[offen]
    .value_counts()             
    .reset_index()
    .head(10)  
    .rename(columns={            
        offen: 'OFFENSE_DESCRIPTION',
        'count': 'summons_count'
     })  
) 
print(offense_descriptions)

             OFFENSE_DESCRIPTION  summons_count
0         CONSUMPTION OF ALCOHOL         248650
1  FEDERAL MOTOR VEH. SAFETY REG         158420
2       MARIJUANA, POSSESSION OF          84910
3            URINATING IN PUBLIC          50340
4               RECKLESS DRIVING          44691
5   ALCOHOLIC BEVERAGE IN PUBLIC          43789
6    FAILURE TO COMPLY WITH SIGN          42810
7                       TRESPASS          38595
8               OTHER ADMIN CODE          31851
9             DISORDERLY CONDUCT          20743

In [14]:
# 3. What are the total number of summons broken down by year?
nypd_summons ['YEAR'] =  pd.to_datetime(nypd_summons['YEAR'])

summons_by_year = (
nypd_summons.groupby('YEAR')
.size()
.reset_index(name='summons_count')
)
print(summons_by_year)

                            YEAR  summons_count
0  1970-01-01 00:00:00.000002015         297748
1  1970-01-01 00:00:00.000002016         267950
2  1970-01-01 00:00:00.000002017         165093
3  1970-01-01 00:00:00.000002018          89895
4  1970-01-01 00:00:00.000002019          85899
5  1970-01-01 00:00:00.000002020          55589
6  1970-01-01 00:00:00.000002021          45717
7  1970-01-01 00:00:00.000002022          58059
8  1970-01-01 00:00:00.000002023         106529
9  1970-01-01 00:00:00.000002024          94542
10 1970-01-01 00:00:00.000002025         117313

In [15]:
##define unusual summons/rare offenses
rare_offenses = 'OFFENSE_DESCRIPTION'

In [16]:
# 4. What were some of the most unusual summons?
rare_offenses = (
    nypd_summons[offen]
    .value_counts()
    .reset_index()
    .tail(10)
    .rename(columns={offen: 'OFFENSE_DESCRIPTION', 'count': 'summons_count'})
)

print(rare_offenses)

                                   OFFENSE_DESCRIPTION  summons_count
770  ALLOW CONSUMPTION BETWEEN 4:00 AM - 12 NOON (S...              1
771                        TRANSFER WITHOUT PERMISSION              1
772  RECEPTACLES; REMOVING FROM STREET AFTER GARBAG...              1
773          ANIMAL/DOG IN PARK BUILDING/BATH FACILITY              1
774  MORE THAN ONE; APPLY FOR/ACCEPT WITHOUT WRITTE...              1
775  ACCIDENT WITH INJURY/DAMAGE; FAIL TO STOP AND ...              1
776                                 DRIVE THRU BARRIER              1
777                       NO PARKING (STREET CLEANING)              1
778                                     METER (BROKEN)              1
779                                  BICYCLE NO LIGHTS              1

In [17]:
# 5. What is the count of summons by gender?

##define gender summons

gender = 'SEX'

gender = (
    nypd_summons[offen]
    .value_counts()
    .reset_index()
    .rename(columns={offen: 'SEX', 'count': 'summons_count'})
)

print(gender)

                                                   SEX  summons_count
0                               CONSUMPTION OF ALCOHOL         248650
1                        FEDERAL MOTOR VEH. SAFETY REG         158420
2                             MARIJUANA, POSSESSION OF          84910
3                                  URINATING IN PUBLIC          50340
4                                     RECKLESS DRIVING          44691
..                                                 ...            ...
775  ACCIDENT WITH INJURY/DAMAGE; FAIL TO STOP AND ...              1
776                                 DRIVE THRU BARRIER              1
777                       NO PARKING (STREET CLEANING)              1
778                                     METER (BROKEN)              1
779                                  BICYCLE NO LIGHTS              1

[780 rows x 2 columns]

In [18]:
# 6. How many summons were issued by race?

##define race summons

race_summons = 'RACE'

race = (
    nypd_summons[offen]
    .value_counts()
    .reset_index()
    .rename(columns={offen: 'RACE', 'count': 'summons_count'})
)

print(race)

                                                  RACE  summons_count
0                               CONSUMPTION OF ALCOHOL         248650
1                        FEDERAL MOTOR VEH. SAFETY REG         158420
2                             MARIJUANA, POSSESSION OF          84910
3                                  URINATING IN PUBLIC          50340
4                                     RECKLESS DRIVING          44691
..                                                 ...            ...
775  ACCIDENT WITH INJURY/DAMAGE; FAIL TO STOP AND ...              1
776                                 DRIVE THRU BARRIER              1
777                       NO PARKING (STREET CLEANING)              1
778                                     METER (BROKEN)              1
779                                  BICYCLE NO LIGHTS              1

[780 rows x 2 columns]

# 2020 Census population
```python
populations = {
    "BROOKLYN": 2736074,
    "QUEENS": 2405464,
    "MANHATTAN": 1694251,
    "BRONX": 1472654,
    "STATEN ISLAND": 495747
}
```

In [19]:
#7. Which borough had the fewest offenses per 100K people?


# 2020 Census population
populations = {
    "BROOKLYN": 2736074,
    "QUEENS": 2405464,
    "MANHATTAN": 1694251,
    "BRONX": 1472654,
    "STATEN ISLAND": 495747
}

In [26]:
## answer to above 

##define summons by borough
summons_by_borough = (
    nypd_summons.groupby('BORO')
    .size()
    .reset_index(name='summons_count')
        )

#add population and calculate per 100K
summons_by_borough['population'] = summons_by_borough['BORO'].map(populations)
summons_by_borough['per_100k'] = (
    summons_by_borough['summons_count'] / summons_by_borough['population'] * 100000
).round(2)

## sort to find fewest
summons_by_borough = summons_by_borough.sort_values('per_100k')

print(summons_by_borough)

summons_by_borough = summons_by_borough.sort_values('per_100k')

display(summons_by_borough)

fewest = summons_by_borough.iloc[0]
print(f"{fewest['BORO']} had the fewest offenses per 100K people ({fewest['per_100k']})")

            BORO  summons_count  population  per_100k
5  STATEN ISLAND          46824    495747.0   9445.14
4         QUEENS         246314   2405464.0  10239.77
1       BROOKLYN         427679   2736074.0  15631.12
2      MANHATTAN         275884   1694251.0  16283.54
0          BRONX         312327   1472654.0  21208.44
3       NEW YORK          63056         NaN       NaN

            BORO  summons_count  population  per_100k
5  STATEN ISLAND          46824    495747.0   9445.14
4         QUEENS         246314   2405464.0  10239.77
1       BROOKLYN         427679   2736074.0  15631.12
2      MANHATTAN         275884   1694251.0  16283.54
0          BRONX         312327   1472654.0  21208.44
3       NEW YORK          63056         NaN       NaN

STATEN ISLAND had the fewest offenses per 100K people (9445.14)